"""LLM prompt templates."""

from app.prompts.templates import (
    ATS_BOOST_PROMPT,
    CRITICAL_TRUTHFULNESS_RULES,
    DEFAULT_IMPROVE_PROMPT_ID,
    DIFF_IMPROVE_PROMPT,
    DIFF_STRATEGY_INSTRUCTIONS,
    EXTRACT_KEYWORDS_PROMPT,
    IMPROVE_RESUME_PROMPTS,
    PARSE_RESUME_PROMPT,
    QUANTIFY_BULLETS_PROMPT,
    RESUME_SCHEMA_EXAMPLE,
    IMPROVE_SCHEMA_EXAMPLE,
    get_language_name,
)

__all__ = [
    "ATS_BOOST_PROMPT",
    "QUANTIFY_BULLETS_PROMPT",
    "PARSE_RESUME_PROMPT",
    "EXTRACT_KEYWORDS_PROMPT",
    "IMPROVE_RESUME_PROMPTS",
    "DEFAULT_IMPROVE_PROMPT_ID",
    "CRITICAL_TRUTHFULNESS_RULES",
    "DIFF_IMPROVE_PROMPT",
    "DIFF_STRATEGY_INSTRUCTIONS",
    "RESUME_SCHEMA_EXAMPLE",
    "IMPROVE_SCHEMA_EXAMPLE",
    "get_language_name",
]
